# RETURN VALUES #
OK =  		0
ERROR    = 	-1
INVALID  = 	-2
NOTFOUND = 	-4

# LIST OF IDs #
WEB = 		100
ASTERISK = 	101
ALARMS = 	102
MANAGER = 	105
SYSTEM = 	200

# TAGS #
TAG_ID = 	"ID"
TAG_CMD = 	"CMD"
TAG_INFO = 	"INFO"
TAG_DATA = 	"DATA"
TAG_FROM = 	"FROM"
TAG_CONTENT = 	"CONTENT"
TAG_HOWMANY = 	"HOWMANY"
TAG_BLOW = 	"BLOW"
TAG_PART = 	"PART"

# DATA #
DATA_ORG 	= "org"
DATA_MSG 	= "msg"
DATA_BLOW 	= "blow"
DATA_OPER 	= "oper"
DATA_DESTN 	= "dest_number"
DATA_EXT 	= "extension"

# LOG LEVELS #
LOG_INFO     = 10
LOG_ERROR    = 11
LOG_CRITICAL = 12

# MISC #
MAX_CONNECTIONS = 5
MSG_SIZE = 1024


# FILE NAMES #
SMS_LOGNAME = 	"sms.log"
DBCOM_LOGNAME = "dbcom.log"
ALARM_LOGNAME = "alarm.log"

# DATABASE DEFINITIONS #
DB_HOST = "127.0.0.1"
DB_USER = "root"
DB_PASS = "root"
DB_NAME = "senas"

TABLE_USER = "user"
TABLE_SMS  = "sms"

# LIST OF COMMANDS #
CMD_HALT 	= "halt"
CMD_CLEAN_LOG 	= "clean_log"
CMD_SEND_SMS 	= "send_sms"
CMD_LOGIN 	= "login"
CMD_BLOW 	= "blow"

# LIST OF ALARMS STATE #
ACTIVE = 	0
CANCELED = 	1
FAILED = 	2
SENT = 		3

# GSM COMMUNICATION #
GSM_ATCOM 	= 20
GSM_ASTERISK 	= 21
