#!/bin/bash

# do with a makefile #

echo "rm -f ./*.pyc"
rm -f ./*.pyc
echo "cd log; rm -f *.log; cd ../"
cd log; rm -f *.log; cd ../
echo "cd interfaces; rm -f *.pyc; cd ../"
cd interfaces; rm -f *.pyc; cd ../
echo "cd libs; rm -f *.pyc"
cd libs; rm -f *.pyc
echo "cd log; rm -f *.pyc;"
cd log; rm -f *.pyc;
echo "cd ../defines; rm -f *.pyc"
cd ../defines; rm -f *.pyc
echo "cd ../shared; rm -f *.pyc"
cd ../shared; rm -f *.pyc
echo "cd ../alarm; rm -f *.pyc"
cd ../alarm; rm -f *.pyc
echo "cd ../dbcom; rm -f *.pyc"
cd ../gsmcom; rm -f *.pyc
echo "cd ../gsmcom; rm -f *.pyc"
cd ../dbcom; rm -f *.pyc
